### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'componentConfig')

### ISSUE THREAD

**Issue by jiangslee** [wlllyfor/taro-vue3#1]
@vue/cli 4.5.13
yarn install v1.22.11
npm 8.1.2
nodejs v16.13.2

```
yarn dev:weapp
```

```
yarn run v1.22.11
$ npm run build:weapp -- --watch

> taro-vue3@1.0.0 build:weapp
> taro build --type weapp "--watch"

👽 Taro v3.4.1

Tips: 预览模式生成的文件较大，设置 NODE_ENV 为 production 可以开启压缩。
Example:
$ NODE_ENV=production taro build --type weapp --watch

启动  开发者工具-项目目录  /Users/jiangslee/taro/taro-vue3/dist
生成  工具配置  /Users/jiangslee/taro/taro-vue3/dist/project.config.json

编译  发现入口  src/app.ts
编译  发现页面  src/pages/create/index.vue
编译  发现页面  src/pages/find/index.vue
编译  发现页面  src/pages/my/index.vue
编译  发现页面  src/pagesSub/search/index.vue
编译  发现页面  src/pagesSub/my/detail/index.vue
编译  发现页面  src/pagesSub/my/about/index.vue
编译  发现页面  src/pagesSub/book/detail/index.vue
🙅   编译失败. 2022/1/26 下午4:11:54

./src/pages/find/index.vue?vue&type=template&id=73679080&ts=true)
Module build failed (from ./node_modules/vue-loader/dist/templateLoader.js):
TypeError: Cannot read properties of undefined (reading 'componentConfig')


监听文件修改中...

./src/pages/find/index.vue?vue&type=template&id=73679080&ts=true (./node_modules/babel-loader/lib!./node_modules/vue-loader/dist/templateLoader.js??ref--6!./node_modules/vue-loader/dist??ref--10-0!./src/pages/find/index.vue?vue&type=template&id=73679080&ts=true)
Module build failed (from ./node_modules/vue-loader/dist/templateLoader.js):
TypeError: Cannot read properties of undefined (reading 'componentConfig')
    at Array.<anonymous> (/Users/jiangslee/taro/taro-vue3/node_modules/@tarojs/plugin-framework-vue3/src/webpack.mini.ts:67:35)
    at traverseNode (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2154:41)
    at traverseChildren (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2145:9)
    at traverseNode (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2196:13)
    at transform (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2078:5)
    at Object.baseCompile (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:5662:5)
    at Object.compile (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-dom/dist/compiler-dom.cjs.js:3063:25)
    at doCompileTemplate (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:3144:49)
    at Object.compileTemplate (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:3117:16)
    at Object.TemplateLoader (/Users/jiangslee/taro/taro-vue3/node_modules/vue-loader/dist/templateLoader.js:35:42)
 @ ./src/pages/find/index.vue?vue&type=template&id=73679080&ts=true 1:0-237 1:0-237
 @ ./node_modules/@tarojs/taro-loader/lib/raw.js!./src/pages/find/index.vue
 @ ./src/pages/find/index.vue,./src/pagesSub/my/detail/index.vue?vue&type=template&id=4da519bd&ts=true (./node_modules/babel-loader/lib!./node_modules/vue-loader/dist/templateLoader.js??ref--6!./node_modules/vue-loader/dist??ref--10-0!./src/pagesSub/my/detail/index.vue?vue&type=template&id=4da519bd&ts=true)
Module build failed (from ./node_modules/vue-loader/dist/templateLoader.js):
TypeError: Cannot read properties of undefined (reading 'componentConfig')
    at Array.<anonymous> (/Users/jiangslee/taro/taro-vue3/node_modules/@tarojs/plugin-framework-vue3/src/webpack.mini.ts:67:35)
    at traverseNode (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2154:41)
    at traverseChildren (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2145:9)
    at traverseNode (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2196:13)
    at transform (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2078:5)
    at Object.baseCompile (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:5662:5)
    at Object.compile (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-dom/dist/compiler-dom.cjs.js:3063:25)
    at doCompileTemplate (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:3144:49)
    at Object.compileTemplate (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:3117:16)
    at Object.TemplateLoader (/Users/jiangslee/taro/taro-vue3/node_modules/vue-loader/dist/templateLoader.js:35:42)
 @ ./src/pagesSub/my/detail/index.vue?vue&type=template&id=4da519bd&ts=true 1:0-246 1:0-246
 @ ./node_modules/@tarojs/taro-loader/lib/raw.js!./src/pagesSub/my/detail/index.vue
 @ ./src/pagesSub/my/detail/index.vue,./src/pagesSub/book/detail/index.vue?vue&type=template&id=da657ac0&ts=true (./node_modules/babel-loader/lib!./node_modules/vue-loader/dist/templateLoader.js??ref--6!./node_modules/vue-loader/dist??ref--10-0!./src/pagesSub/book/detail/index.vue?vue&type=template&id=da657ac0&ts=true)
Module build failed (from ./node_modules/vue-loader/dist/templateLoader.js):
TypeError: Cannot read properties of undefined (reading 'componentConfig')
    at Array.<anonymous> (/Users/jiangslee/taro/taro-vue3/node_modules/@tarojs/plugin-framework-vue3/src/webpack.mini.ts:67:35)
    at traverseNode (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2154:41)
    at traverseChildren (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2145:9)
    at traverseNode (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2196:13)
    at transform (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2078:5)
    at Object.baseCompile (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:5662:5)
    at Object.compile (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-dom/dist/compiler-dom.cjs.js:3063:25)
    at doCompileTemplate (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:3144:49)
    at Object.compileTemplate (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:3117:16)
    at Object.TemplateLoader (/Users/jiangslee/taro/taro-vue3/node_modules/vue-loader/dist/templateLoader.js:35:42)
 @ ./src/pagesSub/book/detail/index.vue?vue&type=template&id=da657ac0&ts=true 1:0-246 1:0-246
 @ ./node_modules/@tarojs/taro-loader/lib/raw.js!./src/pagesSub/book/detail/index.vue
 @ ./src/pagesSub/book/detail/index.vue,./src/pagesSub/book/detail/headerDetail.vue?vue&type=template&id=531043e0&ts=true (./node_modules/babel-loader/lib!./node_modules/vue-loader/dist/templateLoader.js??ref--6!./node_modules/vue-loader/dist??ref--10-0!./src/pagesSub/book/detail/headerDetail.vue?vue&type=template&id=531043e0&ts=true)
Module build failed (from ./node_modules/vue-loader/dist/templateLoader.js):
TypeError: Cannot read properties of undefined (reading 'componentConfig')
    at Array.<anonymous> (/Users/jiangslee/taro/taro-vue3/node_modules/@tarojs/plugin-framework-vue3/src/webpack.mini.ts:67:35)
    at traverseNode (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2154:41)
    at traverseChildren (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2145:9)
    at traverseNode (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2196:13)
    at transform (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2078:5)
    at Object.baseCompile (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:5662:5)
    at Object.compile (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-dom/dist/compiler-dom.cjs.js:3063:25)
    at doCompileTemplate (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:3144:49)
    at Object.compileTemplate (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:3117:16)
    at Object.TemplateLoader (/Users/jiangslee/taro/taro-vue3/node_modules/vue-loader/dist/templateLoader.js:35:42)
 @ ./src/pagesSub/book/detail/headerDetail.vue?vue&type=template&id=531043e0&ts=true 1:0-253 1:0-253
 @ ./src/pagesSub/book/detail/headerDetail.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/dist??ref--10-0!./src/pagesSub/book/detail/index.vue?vue&type=script&lang=ts&setup=true
 @ ./src/pagesSub/book/detail/index.vue?vue&type=script&lang=ts&setup=true
 @ ./node_modules/@tarojs/taro-loader/lib/raw.js!./src/pagesSub/book/detail/index.vue
 @ ./src/pagesSub/book/detail/index.vue,./src/pages/my/userInfo.vue?vue&type=template&id=35b43748&ts=true (./node_modules/babel-loader/lib!./node_modules/vue-loader/dist/templateLoader.js??ref--6!./node_modules/vue-loader/dist??ref--10-0!./src/pages/my/userInfo.vue?vue&type=template&id=35b43748&ts=true)
Module build failed (from ./node_modules/vue-loader/dist/templateLoader.js):
TypeError: Cannot read properties of undefined (reading 'componentConfig')
    at Array.<anonymous> (/Users/jiangslee/taro/taro-vue3/node_modules/@tarojs/plugin-framework-vue3/src/webpack.mini.ts:67:35)
    at traverseNode (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2154:41)
    at traverseChildren (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2145:9)
    at traverseNode (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2196:13)
    at transform (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2078:5)
    at Object.baseCompile (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:5662:5)
    at Object.compile (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-dom/dist/compiler-dom.cjs.js:3063:25)
    at doCompileTemplate (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:3144:49)
    at Object.compileTemplate (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:3117:16)
    at Object.TemplateLoader (/Users/jiangslee/taro/taro-vue3/node_modules/vue-loader/dist/templateLoader.js:35:42)
 @ ./src/pages/my/userInfo.vue?vue&type=template&id=35b43748&ts=true 1:0-240 1:0-240
 @ ./src/pages/my/userInfo.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/dist??ref--10-0!./src/pages/my/index.vue?vue&type=script&lang=ts&setup=true
 @ ./src/pages/my/index.vue?vue&type=script&lang=ts&setup=true
 @ ./node_modules/@tarojs/taro-loader/lib/raw.js!./src/pages/my/index.vue
 @ ./src/pages/my/index.vue,./src/components/bookList.vue?vue&type=template&id=509cb892&ts=true (./node_modules/babel-loader/lib!./node_modules/vue-loader/dist/templateLoader.js??ref--6!./node_modules/vue-loader/dist??ref--10-0!./src/components/bookList.vue?vue&type=template&id=509cb892&ts=true)
Module build failed (from ./node_modules/vue-loader/dist/templateLoader.js):
TypeError: Cannot read properties of undefined (reading 'componentConfig')
    at Array.<anonymous> (/Users/jiangslee/taro/taro-vue3/node_modules/@tarojs/plugin-framework-vue3/src/webpack.mini.ts:67:35)
    at traverseNode (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2154:41)
    at traverseChildren (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2145:9)
    at traverseNode (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2196:13)
    at transform (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2078:5)
    at Object.baseCompile (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:5662:5)
    at Object.compile (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-dom/dist/compiler-dom.cjs.js:3063:25)
    at doCompileTemplate (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:3144:49)
    at Object.compileTemplate (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:3117:16)
    at Object.TemplateLoader (/Users/jiangslee/taro/taro-vue3/node_modules/vue-loader/dist/templateLoader.js:35:42)
 @ ./src/components/bookList.vue?vue&type=template&id=509cb892&ts=true 1:0-231 1:0-231
 @ ./src/components/bookList.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/dist??ref--10-0!./src/pages/find/index.vue?vue&type=script&lang=ts&setup=true
 @ ./src/pages/find/index.vue?vue&type=script&lang=ts&setup=true
 @ ./node_modules/@tarojs/taro-loader/lib/raw.js!./src/pages/find/index.vue
 @ ./src/pages/find/index.vue,./src/components/basic/enterView.vue?vue&type=template&id=6d78e51c&ts=true (./node_modules/babel-loader/lib!./node_modules/vue-loader/dist/templateLoader.js??ref--6!./node_modules/vue-loader/dist??ref--10-0!./src/components/basic/enterView.vue?vue&type=template&id=6d78e51c&ts=true)
Module build failed (from ./node_modules/vue-loader/dist/templateLoader.js):
TypeError: Cannot read properties of undefined (reading 'componentConfig')
    at Array.<anonymous> (/Users/jiangslee/taro/taro-vue3/node_modules/@tarojs/plugin-framework-vue3/src/webpack.mini.ts:67:35)
    at traverseNode (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2154:41)
    at traverseChildren (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2145:9)
    at traverseNode (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2196:13)
    at transform (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2078:5)
    at Object.baseCompile (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:5662:5)
    at Object.compile (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-dom/dist/compiler-dom.cjs.js:3063:25)
    at doCompileTemplate (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:3144:49)
    at Object.compileTemplate (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:3117:16)
    at Object.TemplateLoader (/Users/jiangslee/taro/taro-vue3/node_modules/vue-loader/dist/templateLoader.js:35:42)
 @ ./src/components/basic/enterView.vue?vue&type=template&id=6d78e51c&ts=true 1:0-241 1:0-241
 @ ./src/components/basic/enterView.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/dist??ref--10-0!./src/components/bookList.vue?vue&type=script&lang=ts&setup=true
 @ ./src/components/bookList.vue?vue&type=script&lang=ts&setup=true
 @ ./src/components/bookList.vue
 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/dist??ref--10-0!./src/pages/find/index.vue?vue&type=script&lang=ts&setup=true
 @ ./src/pages/find/index.vue?vue&type=script&lang=ts&setup=true
 @ ./node_modules/@tarojs/taro-loader/lib/raw.js!./src/pages/find/index.vue
 @ ./src/pages/find/index.vue,./src/pages/my/index.vue?vue&type=template&id=698d409a&ts=true (./node_modules/babel-loader/lib!./node_modules/vue-loader/dist/templateLoader.js??ref--6!./node_modules/vue-loader/dist??ref--10-0!./src/pages/my/index.vue?vue&type=template&id=698d409a&ts=true)
Module build failed (from ./node_modules/vue-loader/dist/templateLoader.js):
TypeError: Cannot read properties of undefined (reading 'componentConfig')
    at Array.<anonymous> (/Users/jiangslee/taro/taro-vue3/node_modules/@tarojs/plugin-framework-vue3/src/webpack.mini.ts:67:35)
    at traverseNode (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2154:41)
    at traverseChildren (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2145:9)
    at traverseNode (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2196:13)
    at traverseNode (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2189:17)
    at traverseChildren (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2145:9)
    at traverseNode (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2196:13)
    at transform (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:2078:5)
    at Object.baseCompile (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-core/dist/compiler-core.cjs.js:5662:5)
    at Object.compile (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-dom/dist/compiler-dom.cjs.js:3063:25)
    at doCompileTemplate (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:3144:49)
    at Object.compileTemplate (/Users/jiangslee/taro/taro-vue3/node_modules/@vue/compiler-sfc/dist/compiler-sfc.cjs.js:3117:16)
    at Object.TemplateLoader (/Users/jiangslee/taro/taro-vue3/node_modules/vue-loader/dist/templateLoader.js:35:42)
 @ ./src/pages/my/index.vue?vue&type=template&id=698d409a&ts=true 1:0-237 1:0-237
 @ ./node_modules/@tarojs/taro-loader/lib/raw.js!./src/pages/my/index.vue
 @ ./src/pages/my/index.vue


node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Array]".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by wlllyfor** [comment]
![image](https://user-images.githubusercontent.com/33924540/151138351-3227febc-bd5b-4460-bf2b-5e382a8175bf.png)
你的taro版本是3.4.1，我那个项目写之前 taro 3.4.1 还没发布，你把 package.json中所有3.3.20的依赖全部换成3.4.1，然后重新安装一下依赖试试。
当然也可以重新clone 一下，我把package.json的taro相关依赖版本更新了。
